coverage:
  status:
    project:
      default:
        threshold: 90%
    patch:
      default:
        threshold: 90%
ignore:
  - "lua/fzfx/commons/*.lua"
  - "lua/fzfx/commons/*/*.lua"
  - "lua/fzfx/commons/*/*/*.lua"
