name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ !contains(github.ref, 'main') }}
permissions:
  contents: write
  pull-requests: write
jobs:
  commit:
    name: Commits
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --config-path .stylua.toml ./lua ./spec ./bin
      - name: Install commons.nvim
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          git clone --depth=1 https://github.com/linrongbin16/commons.nvim.git ~/.commons.nvim
          rm -rf ./lua/fzfx/commons
          cp -rf ~/.commons.nvim/lua/commons ./lua/fzfx/
          cp ~/.commons.nvim/version.txt ./lua/fzfx/commons/version.txt
          find ./lua/fzfx/commons -type f -name '*.lua' -exec sed -i 's/require("commons/require("fzfx.commons/g' {} \;
      - uses: cargo-bins/cargo-binstall@main
      - name: Selene
        run: |
          cargo binstall --no-confirm selene
          selene --config selene.toml ./lua
      - uses: mrcjkb/lua-typecheck-action@v0
        with:
          directories: lua
          configpath: ".luarc.json"
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          commit_message: "chore(pr): auto-commit"
          push_options: "--force"
  unit_test:
    name: Unit Test
    needs:
      - lint
    strategy:
      matrix:
        nvim_version: [stable, nightly, v0.7.0]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"
      - uses: leafo/gh-actions-luarocks@v4
      - name: Run Tests
        run: |
          sudo apt-get -y -qq install bat
          sudo apt-get -y -qq install fzf
          luarocks install luacov
          luarocks install luacov-reporter-lcov
          luarocks install vusted
          vusted --coverage ./spec
      - name: Generate Reports
        run: |
          echo "ls ."
          ls -l .
          echo "run luacov"
          luacov -r lcov
          echo "ls ."
          ls -l .
          echo "tail ./luacov.report.out"
          tail -n 50 ./luacov.report.out
          cp luacov.report.out luacov.report.txt
      - uses: codecov/codecov-action@v4
        with:
          files: luacov.report.txt
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  release:
    name: Release
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - unit_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: fzfx.nvim
      - uses: nvim-neorocks/luarocks-tag-release@v5
        if: ${{ steps.release.outputs.release_created }}
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ steps.release.outputs.tag_name }}
          copy_directories: |
            {{ neovim.plugin.dirs }}
            bin
            docs
            spec
          labels: |
            neovim
            vim
