name: CI
on:
  pull_request: ~
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Neovim Typecheck linter
        uses: stevearc/nvim-typecheck-action@v1
        with:
          path: lua
          level: Information
          configpath: ".luarc.json"
          neodev-version: stable
          nvim-version: v0.9.1
          luals-version: 3.6.25
  luacheck:
    name: Lua check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
        with:
          args: lua --config .luacheckrc
  unit_test_stable:
    name: Unit test on stable nvim
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: stable
      - name: Install luajit
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"
      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Run test cases
        shell: bash
        run: |
          luarocks install luacheck
          luarocks install luacov
          luarocks install cluacov
          luarocks install vusted
          vusted --coverage --shuffle ./test
          echo "ls ."
          ls -l .
          echo "ls ./test"
          ls -l ./test
          echo "ls ./lua"
          ls -l ./test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  unit_test_nightly:
    name: Unit test on nightly nvim
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly
      - name: Install luajit
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"
      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Run test cases
        shell: bash
        run: |
          luarocks install luacheck
          luarocks install vusted
          vusted --shuffle ./test
