name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  conventional_commit:
    name: Conventional Commits
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ytanikin/PRConventionalCommits@1.1.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert","break"]'
  luacheck:
    name: Lua Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install commons.nvim
        if: ${{ github.ref != 'refs/heads/main' }}
        shell: bash
        run: |
          git clone --depth=1 https://github.com/linrongbin16/commons.nvim.git ~/.commons.nvim
          rm -rf ./lua/fzfx/commons
          cp -rf ~/.commons.nvim/lua/commons ./lua/fzfx/
          cp ~/.commons.nvim/version.txt ./lua/fzfx/commons/version.txt
          find ./lua/fzfx/commons -type f -name '*.lua' -exec sed -i 's/"commons./"fzfx.commons./g' {} \;
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --config-path .stylua.toml ./lua ./spec ./bin
      - uses: lunarmodules/luacheck@v1
        with:
          args: lua --config .luacheckrc
      - uses: stevearc/nvim-typecheck-action@v1
        with:
          path: lua
          level: Information
          configpath: ".luarc.json"
          neodev-version: stable
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          commit_message: "chore(pr): auto-commit"
          push_options: "--force"
  unit_test:
    name: Unit Test
    needs:
      - luacheck
    strategy:
      matrix:
        nvim_version: [stable, nightly, v0.7.0]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"
      - uses: leafo/gh-actions-luarocks@v4
      - name: Run Tests
        run: |
          luarocks install vusted
          git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
          ~/.fzf/install
          export PATH="$HOME/.fzf/bin:$PATH"
          vusted --shuffle ./spec
  code_coverage:
    name: Code Coverage
    needs:
      - luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: stable
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"
      - uses: leafo/gh-actions-luarocks@v4
      - name: Run Tests
        run: |
          luarocks install luacov
          luarocks install luacov-reporter-lcov
          luarocks install vusted
          git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
          ~/.fzf/install
          export PATH="$HOME/.fzf/bin:$PATH"
          vusted --coverage ./spec
      - name: Generate coverage reports
        shell: bash
        run: |
          echo "ls ."
          ls -l .
          echo "run luacov"
          luacov -r lcov
          echo "ls ."
          ls -l .
          echo "tail ./luacov.report.out"
          tail -n 50 ./luacov.report.out
          mv luacov.report.out luacov.report.txt
      - uses: codecov/codecov-action@v4
        with:
          files: luacov.report.txt
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  release:
    name: Release
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - unit_test
      - code_coverage
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: fzfx.nvim
      - uses: actions/checkout@v4
      - uses: rickstaa/action-create-tag@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          tag: stable
          message: "Current stable release: ${{ steps.release.outputs.tag_name }}"
          tag_exists_error: false
          force_push_tag: true
      - uses: nvim-neorocks/luarocks-tag-release@v5
        if: ${{ steps.release.outputs.release_created }}
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ steps.release.outputs.tag_name }}
          copy_directories: |
            {{ neovim.plugin.dirs }}
            bin
            docs
            spec
          labels: |
            neovim
            vim
