name: LuaRocks
on:
  push:
    tags:
      - "*"
  pull_request: # Will test a local install without uploading to luarocks.org
concurrency:
  group: ${{ github.ref }}-luarocks
  cancel-in-progress: true
jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
