name: PR
on: pull_request_target
jobs:
  pr_comment:
    name: PR comment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Content
      run: |
        echo "::set-env name=body::$(<./github/PULL_REQUEST_TEMPLATE/pr.md)"   # set it as env
    - name: PR Comment
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const creator = context.payload.sender.login
          await github.rest.pulls.createReviewComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            body: `Hi ${creator}, thanks to your contribute, while please check below tasks.

# Regresion test

## Platform

- [ ] windows
- [ ] macOS/linux

## Tasks

- [ ] FzfxFiles
  - [ ] Press `CTRL-U`/`CTRL-R` to switch between restricted/unrestricted mode, and the lines count is consistent when press multiple times.
  - [ ] Use `V`/`W`/`P` variants (visual selection, cursor word, yank text).
  - [ ] Press `ESC` to quit, `ENTER` to open file.
- [ ] FzfxLiveGrep
  - [ ] Press `CTRL-U`/`CTRL-R` to switch between restricted/unrestricted mode, and the lines count is consistent when press multiple times.
  - [ ] Use `-w` to match word only, use `-g *.lua` to search only lua files.
  - [ ] Use `V`/`W`/`P` variants (visual selection, cursor word, yank text).
  - [ ] Press `ESC` to quit, `ENTER` to open file.
- [ ] FzfxBuffers
  - [ ] Press `CTRL-D` to delete buffers.
  - [ ] Use `V`/`W`/`P` variants (visual selection, cursor word, yank text).
  - [ ] Press `ESC` to quit, `ENTER` to open file.
- [ ] FzfxGFiles
  - [ ] Press `CTRL-U`/`CTRL-W` to switch between workspace/current folder mode.
  - [ ] Use `V`/`W`/`P` variants (visual selection, cursor word, yank text).
  - [ ] Press `ESC` to quit, `ENTER` to open file.
- [ ] FzfxGCommits
  - [ ] Press `CTRL-U`/`CTRL-A` to switch between git repo commits/current buffer commits.
  - [ ] Use `V`/`W`/`P` variants (visual selection, cursor word, yank text).
  - [ ] Press `ESC` to quit, `ENTER` to copy commit hash.
- [ ] FzfxGBlame
  - [ ] Use `V`/`W`/`P` variants (visual selection, cursor word, yank text).
  - [ ] Press `ESC` to quit, `ENTER` to copy commit hash.
- [ ] FzfxLspDiagnostics
  - [ ] Press `CTRL-U`/`CTRL-W` to switch between workspace/current buffer diagnostics.
  - [ ] Use `V`/`W`/`P` variants (visual selection, cursor word, yank text).
  - [ ] Press `ESC` to quit, `ENTER` to open file.
- [ ] FzfxLspDefinitions, FzfxLspTypeDefinitions, FzfxLspReferences, FzfxLspImplementations
  - [ ] Go to definitions/references (this is the most 2 easiest use case when developing this lua plugin with lua_ls).
  - [ ] Press `ESC` to quit, `ENTER` to open file.
- [ ] FzfxFileExplorer
  - [ ] Press `CTRL-U`/`CTRL-I` to switch between filter/include hidden files mode.
  - [ ] Press `CTRL-L`/`CTRL-H` to cd into folder and cd upper folder.
  - [ ] Press `ESC` to quit, `ENTER` to open file.
`
          })
