name: PR
on:
  pull_request: ~
  push:
    branches:
      - main
jobs:
  pr_comment:
    name: PR comment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate coverage reports
      shell: bash
      run: |
          echo "ls -lh ."
          ls -lh .
    - name: PR Comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        filePath: .github/PULL_REQUEST_TEMPLATE/pr.md
