name: PR
on:
  pull_request: ~
  push:
    branches:
      - main
jobs:
  comment_on_open:
    name: Comment on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Comment on PR
        shell: bash
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/linrongbin16/${{ github.repository }}/commits/${{ github.sha }}/comments \
          -d '{"body":"Comment PR"}'
