name: PR
on:
  pull_request: ~
  push:
    branches:
      - main
jobs:
  pr_comment:
    runs-on: ubuntu-latest
    steps:
      - name: PR comment
        uses: actions/github-script@v6
        with:
          script: |
            const body = `# Regression test`;
            await github.rest.pulls.createReviewComment({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
              commit_id: process.env.GITHUB_SHA,
              path: ""
            })
